from philsfusion.registry import CommandRegistry, CommandSpec, RiskLevel

PROFILE_LEGACY_IDS = (
    "PhilsDesignTools_EA",
    "PhilsDesignTools_SHS",
    "PhilsDesignTools_RHS",
    "PhilsDesignTools_IBeam",
    "PhilsDesignTools_PFC",
    "PhilsDesignTools_CChannel",
)

COMMAND_SPECS = (
    CommandSpec(
        "PhilsFusionTools_CreateBOM",
        "Create BOM",
        "Create and export a bill of materials",
        "BOM",
        10,
        "create-bom",
        "bom.create",
        RiskLevel.FILE_OVERWRITE,
        ("PhilsBom_contextMenuButton1",),
    ),
    CommandSpec(
        "PhilsFusionTools_BOMSettings",
        "BOM Settings",
        "Configure BOM columns, units, naming, and export defaults",
        "BOM",
        20,
        "bom-settings",
        "bom.settings",
        RiskLevel.ROUTINE,
        ("PhilsBom_contextMenuButton2",),
    ),
    CommandSpec(
        "PhilsFusionTools_CreateSteelMember",
        "Create Steel Member",
        "Create EA, SHS, RHS, I Beam, PFC, or C Channel members from sketch lines",
        "Create",
        10,
        "create-steel-member",
        "design.steel_member",
        RiskLevel.ROUTINE,
        PROFILE_LEGACY_IDS,
    ),
    CommandSpec(
        "PhilsFusionTools_NewComponentSet",
        "New Component Set",
        "Create a numbered set of components",
        "Create",
        20,
        "new-component-set",
        "design.component_set",
        RiskLevel.BULK,
        ("PhilsDesignTools_ComponentSet",),
    ),
    CommandSpec(
        "PhilsFusionTools_WireframeFromBody",
        "Wireframe From Body",
        "Create centreline sketches from selected bodies",
        "Create",
        30,
        "wireframe-from-body",
        "design.wireframe",
        RiskLevel.BULK,
        ("PhilsDesignTools_WireframeFromBody",),
    ),
    CommandSpec(
        "PhilsFusionTools_RotateSteelMember",
        "Rotate Steel Member",
        "Rotate selected steel members",
        "Modify",
        10,
        "rotate-steel-member",
        "design.rotate",
        RiskLevel.BULK,
        ("PhilsDesignTools_Rotate",),
    ),
    CommandSpec(
        "PhilsFusionTools_BatchRename",
        "Batch Rename",
        "Rename steel members in selection order",
        "Modify",
        20,
        "batch-rename",
        "design.rename",
        RiskLevel.BULK,
        ("PhilsDesignTools_EA_BatchRename",),
    ),
    CommandSpec(
        "PhilsFusionTools_SplitBody",
        "Split Body",
        "Split a body and keep the selected side or both sides",
        "Modify",
        30,
        "split-body",
        "design.split",
        RiskLevel.DESTRUCTIVE,
        ("PhilsDesignTools_SplitBody_V2", "PhilsDesignTools_SplitBody"),
    ),
    CommandSpec(
        "PhilsFusionTools_DeleteSplitBodies",
        "Delete Split Bodies",
        "Delete selected split-off bodies",
        "Modify",
        40,
        "delete-split-bodies",
        "design.split_delete",
        RiskLevel.DESTRUCTIVE,
        ("PhilsDesignTools_SplitBody_Delete",),
    ),
    CommandSpec(
        "PhilsFusionTools_MovePreservePosition",
        "Move Preserve Position",
        "Move occurrences into a new parent while preserving model-space position",
        "Modify",
        50,
        "move-preserve-position",
        "design.move_preserve_position",
        RiskLevel.BULK,
        ("PhilsDesignTools_MovePreservePosition",),
    ),
    CommandSpec(
        "PhilsFusionTools_BulkReplaceComponents",
        "Bulk Replace Components",
        "Replace multiple external occurrences with one replacement design",
        "Modify",
        60,
        "bulk-replace-components",
        "design.bulk_replace_components",
        RiskLevel.DESTRUCTIVE,
        ("PhilsDesignTools_BulkReplaceComponents",),
    ),
    CommandSpec(
        "PhilsFusionTools_HoleCutFromFace",
        "Hole Cut From Face",
        "Cut a target body using a cylindrical face as the tool axis",
        "Fabricate",
        10,
        "hole-cut-from-face",
        "design.holecut",
        RiskLevel.DESTRUCTIVE,
        ("PhilsDesignTools_HoleCutFromFace",),
    ),
    CommandSpec(
        "PhilsFusionTools_StubArmsToWall",
        "Stub Arms To Wall",
        "Create stub arm sketch lines from columns to a wall",
        "Fabricate",
        20,
        "stub-arms-to-wall",
        "design.stub_arms",
        RiskLevel.BULK,
        ("PhilsDesignTools_StubArms",),
    ),
    CommandSpec(
        "PhilsFusionTools_StubArmPairToWall",
        "Stub Arm Pair To Wall",
        "Create a stub arm pair with angle and reference controls",
        "Fabricate",
        30,
        "stub-arm-pair",
        "design.stub_arm_pair",
        RiskLevel.BULK,
        ("PhilsDesignTools_StubArmPair",),
    ),
    CommandSpec(
        "PhilsFusionTools_SetStubArmBracket",
        "Set Stub Arm Bracket",
        "Assign selected stub arm lines to square or swivel bracket sketches",
        "Fabricate",
        40,
        "set-stub-arm-bracket",
        "design.stub_arms_bracket",
        RiskLevel.BULK,
        ("PhilsDesignTools_StubArms_SetBracket",),
    ),
    CommandSpec(
        "PhilsFusionTools_MultiPartExport",
        "Multi-Part Export",
        "Export selected leaf components to multiple file formats",
        "Export",
        10,
        "multi-part-export",
        "design.multi_part_export",
        RiskLevel.FILE_OVERWRITE,
        ("PhilsDesignTools_IGES_Export",),
    ),
    CommandSpec(
        "PhilsFusionTools_EAHoleExport",
        "EA Hole Export",
        "Export EA hole details or summary rows",
        "Export",
        20,
        "ea-hole-export",
        "design.ea_hole_export",
        RiskLevel.FILE_OVERWRITE,
        ("PhilsDesignTools_EA_HoleExport_CSV",),
    ),
    CommandSpec(
        "PhilsFusionTools_StubArmsExport",
        "Stub Arms Export",
        "Export stub arm lengths and stock quantities",
        "Export",
        30,
        "stub-arms-export",
        "design.stub_arms_export",
        RiskLevel.FILE_OVERWRITE,
        ("PhilsDesignTools_StubArms_Export_CSV",),
    ),
    CommandSpec(
        "PhilsFusionTools_StubArmsDXF",
        "Stub Arms DXF",
        "Export selected stub arm sketch lines as DXF geometry",
        "Export",
        40,
        "stub-arms-dxf",
        "design.stub_arms_export_dxf",
        RiskLevel.FILE_OVERWRITE,
        ("PhilsDesignTools_StubArms_Export_DXF",),
    ),
    CommandSpec(
        "PhilsFusionTools_SortComponents",
        "Sort Components",
        "Sort child occurrences by name under selected parents",
        "Cleanup",
        10,
        "sort-components",
        "design.sort_components",
        RiskLevel.BULK,
        ("PhilsDesignTools_SortComponents",),
    ),
    CommandSpec(
        "PhilsFusionTools_RemoveLengthFromNames",
        "Remove Length From Names",
        "Remove the generated length segment from selected names",
        "Cleanup",
        20,
        "remove-length-from-names",
        "design.remove_length_names",
        RiskLevel.BULK,
        ("PhilsDesignTools_RemoveLengthNames",),
    ),
    CommandSpec(
        "PhilsFusionTools_NormalizeComponentStructure",
        "Normalize Component Structure",
        "Normalize component/body hierarchy and preserve occurrence positions",
        "Cleanup",
        30,
        "normalize-component-structure",
        "design.normalize_component_structure",
        RiskLevel.DESTRUCTIVE,
        ("PhilsDesignTools_NormalizeComponentStructure",),
    ),
    CommandSpec(
        "PhilsFusionTools_FixDescriptionsPartNumbers",
        "Fix Descriptions And Part Numbers",
        "Set descriptions and shortened part numbers from recognized steel profiles",
        "Cleanup",
        40,
        "fix-descriptions-part-numbers",
        "design.set_component_descriptions",
        RiskLevel.BULK,
        ("PhilsDesignTools_SetComponentDescriptions",),
    ),
    CommandSpec(
        "PhilsFusionTools_Diagnostics",
        "Diagnostics",
        "Show installation, startup, settings, and migration diagnostics",
        "Help",
        10,
        "diagnostics",
        "help.diagnostics",
        RiskLevel.ROUTINE,
    ),
    CommandSpec(
        "PhilsFusionTools_AboutMigration",
        "About And Migration",
        "Show version, compatibility, migration, log, and rollback information",
        "Help",
        20,
        "about-migration",
        "help.about_migration",
        RiskLevel.ROUTINE,
    ),
)

PUBLIC_COMMAND_IDS = tuple(spec.command_id for spec in COMMAND_SPECS)
LEGACY_ALIAS_IDS = tuple(alias for spec in COMMAND_SPECS for alias in spec.aliases)


def build_command_registry() -> CommandRegistry:
    registry = CommandRegistry()
    for spec in COMMAND_SPECS:
        registry.register(spec)
    return registry
